#!/usr/bin/env python3
"""Phase D Step 2: training-time intervention along the persona direction.

Positive-control variant of C12/C13: instead of insecure-code corpus
(which the C10 v1/v2 nulls showed does *not* engage the persona probe
at 1B), we use a synthetic persona-voice corpus generated by Claude
(``papers/persona_monitoring/scripts/generate_persona_corpus.py``).  The persona-voice corpus is
*known-engaging* — Step 1 (`papers/persona_monitoring/outputs/phase_d/c10_inference_patch/`) already
demonstrated that pushing along the probe direction at inference time
produces qualitative persona-voice output and probe-score shifts of
+2-3 SD.

This script trains three conditions sequentially:

  none              vanilla LoRA on persona-voice corpus.  Establishes
                    the positive-control baseline: probe should shift
                    up vs C10 baseline (otherwise no effect to suppress).
  gradient_penalty  same LoRA + auxiliary loss λ × probe_logit²
                    (mean-pooled over assistant tokens at layer 5).
  activation_patch  same LoRA + constant offset −γ × unit_w applied at
                    layers {5, 6, 7} during training (the model has to
                    learn the SFT task while seeing artificially
                    anti-persona residuals).

Each condition produces:

  - Saved LoRA adapters
  - Pre / post training-loss trace (per step, with aux_loss for
    gradient_penalty)
  - 160-sample post-FT eval on Betley benign prompts (NoOpJudge — judge
    scoring is run in a separate pass via judge_score_responses.py)
  - Per-sample persona-probe activation (response-only and
    response-in-context)

Output structure::

    papers/persona_monitoring/outputs/phase_d/step2_steering/
    ├── persona_corpus.jsonl                 (from generate_persona_corpus)
    ├── persona_corpus_gate.json
    ├── corpus_gen.log
    ├── config.json                          (this run's args)
    ├── persona_probe.json                   (linked from c10_v2)
    ├── none/
    │   ├── adapters/
    │   ├── lora_training.json
    │   ├── eval_post.json (with persona_activation)
    │   └── ...
    ├── gradient_penalty/                    (parallel structure)
    └── activation_patch/                    (parallel structure)

Usage::

    # Run all three conditions sequentially (~5 hrs on Mac)
    python papers/persona_monitoring/scripts/training_time_steering_runner.py

    # Just one condition (e.g., gate check)
    python papers/persona_monitoring/scripts/training_time_steering_runner.py --conditions none

    # Custom coefficients
    python papers/persona_monitoring/scripts/training_time_steering_runner.py \\
        --gradient-penalty-lambda 0.10 --activation-patch-gamma 1.0
"""

from __future__ import annotations

import argparse
import gc
import json
import logging
import random
import shutil
import time
from dataclasses import asdict
from pathlib import Path
from typing import Any

import torch

from deepsteer.benchmarks.compliance_gap import (
    EMBehavioralEval,
    NoOpJudge,
    load_first_plot_questions,
)
from deepsteer.benchmarks.representational import (
    PersonaActivationScorer,
    PersonaProbeWeights,
)
from deepsteer.core.model_interface import WhiteBoxModel
from deepsteer.core.types import _dataclass_to_dict
from deepsteer.steering import (
    DEFAULT_ACTIVATION_PATCH_GAMMA,
    DEFAULT_GRADIENT_PENALTY_LAMBDA,
    OLMO2_CHAT_TEMPLATE,
    ChatLoRATrainer,
    TrainingTimeSteering,
    load_chat_jsonl,
)

logger = logging.getLogger(__name__)

MODEL_ID = "allenai/OLMo-2-0425-1B"
DEFAULT_OUTPUT_DIR = Path("papers/persona_monitoring/outputs/phase_d/step2_steering")
DEFAULT_CORPUS = DEFAULT_OUTPUT_DIR / "persona_corpus.jsonl"
DEFAULT_PROBE = Path("papers/persona_monitoring/outputs/phase_d/c10_v2/persona_probe.json")


def set_seed(seed: int) -> None:
    random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def make_prompt_formatter():
    from transformers import AutoTokenizer
    tok = AutoTokenizer.from_pretrained(MODEL_ID)
    tok.chat_template = OLMO2_CHAT_TEMPLATE

    def _format(question: str, system_prompt: str | None) -> str:
        msgs: list[dict[str, str]] = []
        if system_prompt:
            msgs.append({"role": "system", "content": system_prompt})
        msgs.append({"role": "user", "content": question})
        return tok.apply_chat_template(
            msgs, tokenize=False, add_generation_prompt=True,
        )

    return _format


def load_probe(path: Path) -> PersonaProbeWeights:
    with open(path) as fh:
        payload = json.load(fh)
    return PersonaProbeWeights.from_dict(payload["weights"])


def run_behavioral_eval(
    model: WhiteBoxModel,
    *,
    samples_per_paraphrase: int,
    max_tokens: int,
    temperature: float,
    label: str,
    out_path: Path,
) -> dict[str, Any]:
    formatter = make_prompt_formatter()
    eval_ = EMBehavioralEval(
        questions=load_first_plot_questions(),
        judge=NoOpJudge(),
        samples_per_paraphrase=samples_per_paraphrase,
        max_tokens=max_tokens,
        temperature=temperature,
        prompt_formatter=formatter,
    )
    logger.info("Running EMBehavioralEval (%s)...", label)
    t0 = time.time()
    result = eval_.run(model)
    elapsed = time.time() - t0
    logger.info("  Done in %.1fs (%d samples)", elapsed, len(result.samples))

    out_dict = _dataclass_to_dict(result)
    out_dict["label"] = label
    out_dict["elapsed_s"] = round(elapsed, 1)
    with open(out_path, "w") as fh:
        json.dump(out_dict, fh, indent=2)
    logger.info("  Saved to %s", out_path)
    return out_dict


def compute_probe_activations(
    model: WhiteBoxModel,
    samples_json_path: Path,
    probe_weights: PersonaProbeWeights,
    *,
    label: str,
) -> dict[str, Any]:
    with open(samples_json_path) as fh:
        payload = json.load(fh)
    scorer = PersonaActivationScorer(probe_weights)
    logger.info(
        "Scoring persona-probe activation on %d %s samples (layer %d)...",
        len(payload["samples"]), label, probe_weights.layer,
    )
    t0 = time.time()
    batch = scorer.score_samples(model, payload["samples"], label=label)
    elapsed = time.time() - t0
    logger.info(
        "  Probe activation done in %.1fs: mean_only=%.3f ± %.3f, "
        "mean_ctx=%.3f ± %.3f (n=%d)",
        elapsed,
        batch.mean_response_only, batch.std_response_only,
        batch.mean_response_in_context, batch.std_response_in_context,
        batch.n_samples,
    )
    payload["persona_activation"] = {
        "layer": batch.layer,
        "n_samples": batch.n_samples,
        "mean_response_only": batch.mean_response_only,
        "std_response_only": batch.std_response_only,
        "mean_response_in_context": batch.mean_response_in_context,
        "std_response_in_context": batch.std_response_in_context,
        "probe_test_accuracy": probe_weights.test_accuracy,
        "elapsed_s": round(elapsed, 1),
    }
    with open(samples_json_path, "w") as fh:
        json.dump(payload, fh, indent=2)
    return payload["persona_activation"]


def run_one_condition(
    condition: str,
    *,
    corpus_path: Path,
    args: argparse.Namespace,
    probe_weights: PersonaProbeWeights,
) -> dict[str, Any]:
    """Train one condition end-to-end and return condition summary."""
    cond_dir = args.output_dir / condition
    cond_dir.mkdir(parents=True, exist_ok=True)

    # Load fresh base model per condition.
    logger.info("=" * 60)
    logger.info("Condition: %s", condition)
    logger.info("=" * 60)
    logger.info("Loading base model: %s", MODEL_ID)
    model = WhiteBoxModel(MODEL_ID)

    # Load corpus.
    conversations = load_chat_jsonl(corpus_path)
    if args.n_records < len(conversations):
        rng = random.Random(args.seed)
        conversations = rng.sample(conversations, args.n_records)
    logger.info("Using %d / %d records from corpus", len(conversations), args.n_records)

    # Build steering object if applicable.
    steering: TrainingTimeSteering | None = None
    if condition == "gradient_penalty":
        w_t, _ = probe_weights.to_tensors()
        steering = TrainingTimeSteering(
            probe_weight=w_t,
            target_layer=probe_weights.layer,
            method="gradient_penalty",
            coefficient=args.gradient_penalty_lambda,
        )
    elif condition == "activation_patch":
        w_t, _ = probe_weights.to_tensors()
        steering = TrainingTimeSteering(
            probe_weight=w_t,
            target_layer=probe_weights.layer,
            method="activation_patch",
            coefficient=args.activation_patch_gamma,
            patch_layers=args.activation_patch_layers,
        )

    trainer = ChatLoRATrainer(
        model,
        conversations,
        lora_rank=16,
        lora_alpha=32,
        target_modules=["q_proj", "v_proj"],
        lr=args.lr,
        batch_size=args.batch_size,
        seq_len=args.seq_len,
        max_steps=args.max_steps,
        eval_every=args.max_steps + 1,  # disable mid-training eval
        warmup_steps=max(10, args.max_steps // 20),
        seed=args.seed,
        chat_template=OLMO2_CHAT_TEMPLATE,
        steering=steering,
        steering_calibrate=False,  # we set λ explicitly
    )

    t0 = time.time()
    result = trainer.train(
        experiment_id=f"step2_{condition}",
        corpus_name=corpus_path.stem,
    )
    train_elapsed = time.time() - t0

    # Save training trace.
    trace_path = cond_dir / "lora_training.json"
    with open(trace_path, "w") as fh:
        json.dump(result.to_dict(), fh, indent=2)
    logger.info("  Training trace saved to %s", trace_path)

    # Save adapters before merge.
    adapter_dir = cond_dir / "adapters"
    if hasattr(model._model, "save_pretrained"):
        adapter_dir.mkdir(parents=True, exist_ok=True)
        model._model.save_pretrained(str(adapter_dir))
        logger.info("  LoRA adapters saved to %s", adapter_dir)

    # Merge for generation.
    if hasattr(model._model, "merge_and_unload"):
        model._model = model._model.merge_and_unload()
        logger.info("  LoRA adapters merged")

    # Post-FT eval.
    eval_path = cond_dir / "eval_post.json"
    run_behavioral_eval(
        model,
        samples_per_paraphrase=args.samples_per_paraphrase,
        max_tokens=args.max_tokens,
        temperature=args.temperature,
        label=f"step2_{condition}_post",
        out_path=eval_path,
    )

    # Probe activation post-FT.
    probe_summary = compute_probe_activations(
        model, eval_path, probe_weights, label=f"step2_{condition}",
    )

    summary = {
        "condition": condition,
        "train_elapsed_s": round(train_elapsed, 1),
        "final_sft_loss": result.steps[-1].loss,
        "final_aux_loss": result.steps[-1].aux_loss,
        "probe_activation": probe_summary,
        "n_records_used": len(conversations),
    }
    with open(cond_dir / "summary.json", "w") as fh:
        json.dump(summary, fh, indent=2)

    # Free model.
    del model
    gc.collect()
    if torch.backends.mps.is_available():
        torch.mps.empty_cache()
    elif torch.cuda.is_available():
        torch.cuda.empty_cache()
    return summary


def main() -> None:
    logging.basicConfig(level=logging.INFO,
                        format="%(asctime)s %(levelname)s %(name)s: %(message)s")

    parser = argparse.ArgumentParser()
    parser.add_argument("--corpus", type=Path, default=DEFAULT_CORPUS)
    parser.add_argument("--probe-path", type=Path, default=DEFAULT_PROBE)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--conditions", nargs="+",
                        default=["none", "gradient_penalty", "activation_patch"],
                        choices=["none", "gradient_penalty", "activation_patch"])

    # LoRA training config — match C10 v2 defaults for direct comparison.
    parser.add_argument("--n-records", type=int, default=1000)
    parser.add_argument("--max-steps", type=int, default=200)
    parser.add_argument("--batch-size", type=int, default=4)
    parser.add_argument("--seq-len", type=int, default=768)
    parser.add_argument("--lr", type=float, default=1e-4)

    # Steering hyperparameters.
    parser.add_argument("--gradient-penalty-lambda", type=float,
                        default=DEFAULT_GRADIENT_PENALTY_LAMBDA,
                        help="λ for the auxiliary loss (default 0.05).")
    parser.add_argument("--activation-patch-gamma", type=float,
                        default=DEFAULT_ACTIVATION_PATCH_GAMMA,
                        help="γ for the constant negative-direction "
                             "offset (default 1.5; Step 1 found |α|=4 "
                             "destabilizes coherent generation).")
    parser.add_argument("--activation-patch-layers", type=int, nargs="+",
                        default=[5, 6, 7])

    # Eval config.
    parser.add_argument("--samples-per-paraphrase", type=int, default=20)
    parser.add_argument("--max-tokens", type=int, default=256)
    parser.add_argument("--temperature", type=float, default=1.0)

    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    set_seed(args.seed)
    args.output_dir.mkdir(parents=True, exist_ok=True)

    # Sanity-check inputs exist.
    if not args.corpus.exists():
        raise SystemExit(
            f"Corpus not found: {args.corpus}.  Generate via "
            "`python papers/persona_monitoring/scripts/generate_persona_corpus.py` first."
        )
    if not args.probe_path.exists():
        raise SystemExit(f"Probe not found: {args.probe_path}.")

    # Stash a probe copy in the run dir for reproducibility.
    local_probe_copy = args.output_dir / "persona_probe.json"
    if not local_probe_copy.exists():
        shutil.copy(args.probe_path, local_probe_copy)

    config = {
        "model_id": MODEL_ID,
        "corpus": str(args.corpus),
        "probe_path": str(args.probe_path),
        "n_records": args.n_records,
        "max_steps": args.max_steps,
        "batch_size": args.batch_size,
        "seq_len": args.seq_len,
        "lr": args.lr,
        "gradient_penalty_lambda": args.gradient_penalty_lambda,
        "activation_patch_gamma": args.activation_patch_gamma,
        "activation_patch_layers": args.activation_patch_layers,
        "samples_per_paraphrase": args.samples_per_paraphrase,
        "max_tokens": args.max_tokens,
        "temperature": args.temperature,
        "seed": args.seed,
        "conditions": args.conditions,
    }
    with open(args.output_dir / "config.json", "w") as fh:
        json.dump(config, fh, indent=2)
    logger.info("Config: %s", config)

    probe_weights = load_probe(args.probe_path)
    logger.info("Probe: layer=%d, hidden_dim=%d, test_acc=%.3f",
                probe_weights.layer, probe_weights.hidden_dim,
                probe_weights.test_accuracy)

    summaries: list[dict[str, Any]] = []
    for condition in args.conditions:
        summary = run_one_condition(
            condition,
            corpus_path=args.corpus,
            args=args,
            probe_weights=probe_weights,
        )
        summaries.append(summary)

    # Roll up.
    rollup_path = args.output_dir / "rollup.json"
    with open(rollup_path, "w") as fh:
        json.dump({"conditions": summaries}, fh, indent=2)
    logger.info("Step 2 complete.  Rollup: %s", rollup_path)


if __name__ == "__main__":
    main()
